### PR TITLE
Semantic class names

### PR DESCRIPTION
**Pull request by dbtek**
- Variable names, class names updated to be more semantic.
- Bootstrap version updated to 3.3.2.
- Ready for 0.2.0 release.

### CODE REVIEW

**Comment by dbtek** [comment]
Due to the major changes, you may think this PR is inappropriate. I thought it would fit to Bootstrap naming concepts in this way.

**Comment by BenWhitehead** [comment]
Thanks for the PR, I think the new names are conceptually okay. The reason I had them they way they were is I ran into an issue with less variables not working. But I don't think thats an issue anymore with the changes to the bootstrap functions for generating the classes.

Can you also open another PR which updates the GH pages to include the new versions of the docs?

Once that PR is up I'll merge this PR. And the docs update.

**Comment by dbtek** [comment]
Hi @BenWhitehead,

Can you draft a release with 0.2.0 tag? A decent changelog would help previous users.

Thanks!

**Comment by BenWhitehead** [comment]
done. https://github.com/BenWhitehead/bootstrap-big-grid/releases/tag/v0.2.0 Thanks for the PRs

**Pull request merged**
